# GIRA - Extrair disponibilidade bicicletas

Manuel Banza - February, 2022

In [2]:
import requests
from requests.structures import CaseInsensitiveDict
import pandas as pd
import datetime
import time

In [67]:
# Obter dados do emel open data: https://emel.city-platform.com/opendata/

url = "https://emel.city-platform.com/opendata/gira/station/list"

headers = CaseInsensitiveDict()
headers["accept"] = "application/json"
headers["api_key"] = "f90859a793cda8a701dd7c25adf5ae2c"


resp = requests.get(url, headers=headers)

#print(resp.status_code)

json = resp.json()
results = json['features']

df = pd.DataFrame(results)
df = df[['properties']]


df = pd.json_normalize(df['properties'])

# Passar para date e criar coluna datetime
df['update_date'] = df['update_date'].astype(str).str[:-1]
df['update_date'] = pd.to_datetime(df['update_date'], format='%Y-%m-%dT%H:%M:%S')
df['update_date_hour'] = df['update_date'].dt.hour
df['update_date_only'] = df['update_date'].dt.date

# cirar latitude e longitude
df['bbox'] = df['bbox'].astype(str).str.replace(']', '')
df['bbox'] = df['bbox'].astype(str).str.replace('[', '')
df[['longitude', 'latitude', 'lon2', 'lat2']] = df['bbox'].str.split(', ', expand=True)

# Eliminar coluna position
df = df.drop(columns=['lon2', 'lat2'])

df.head()

<ipython-input-67-6fed09be3979>:30: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['bbox'] = df['bbox'].astype(str).str.replace(']', '')
<ipython-input-67-6fed09be3979>:31: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['bbox'] = df['bbox'].astype(str).str.replace('[', '')

,id_expl,id_planeamento,desig_comercial,tipo_servico_niveis,num_bicicletas,num_docas,racio,estado,update_date,bbox,update_date_hour,update_date_only,longitude,latitude
0,223,223,223 - Praça do Rossio,,4,21,0.19,active,2022-02-09 15:41:29,"-9.138952, 38.713112, -9.138952, 38.713112",15,2022-02-09,-9.138952,38.713112
1,220,220,220 - Rua do Comercio,,13,20,0.65,active,2022-02-09 15:41:29,"-9.137125, 38.70878, -9.137125, 38.70878",15,2022-02-09,-9.137125,38.70878
2,226,226,226 - Rua dos Fanqueiros,,10,17,0.59,active,2022-02-09 15:41:30,"-9.136456, 38.711888, -9.136456, 38.711888",15,2022-02-09,-9.136456,38.711888
3,315,315,315 - Rua Passos Manuel/ Jardim Constantino,A,2,20,0.10,active,2022-02-09 15:41:30,"-9.136968, 38.731264, -9.136968, 38.731264",15,2022-02-09,-9.136968,38.731264
4,137,137,137 - Rua Cidade de Bissau (entrada SPACIO),A,0,33,0.00,repair,2022-02-09 15:41:31,"-9.114505, 38.762829, -9.114505, 38.762829",15,2022-02-09,-9.114505,38.762829

In [68]:
# Passar para date e criar coluna datetime
print(df.update_date.min())
print(df.update_date.max())
df.head(3)

2022-02-09 15:41:05
2022-02-09 15:41:31

,id_expl,id_planeamento,desig_comercial,tipo_servico_niveis,num_bicicletas,num_docas,racio,estado,update_date,bbox,update_date_hour,update_date_only,longitude,latitude
0,223,223,223 - Praça do Rossio,,4,21,0.19,active,2022-02-09 15:41:29,"-9.138952, 38.713112, -9.138952, 38.713112",15,2022-02-09,-9.138952,38.713112
1,220,220,220 - Rua do Comercio,,13,20,0.65,active,2022-02-09 15:41:29,"-9.137125, 38.70878, -9.137125, 38.70878",15,2022-02-09,-9.137125,38.70878
2,226,226,226 - Rua dos Fanqueiros,,10,17,0.59,active,2022-02-09 15:41:30,"-9.136456, 38.711888, -9.136456, 38.711888",15,2022-02-09,-9.136456,38.711888

In [ ]:
# Get today date now to file name when export to csv or excel with encoding utf8
from datetime import datetime
df.to_csv(datetime.now().strftime('data_sources/data_transformed/gira_disponibilidade_emel_opendata-%Y-%m-%d-%H-%M-%S.csv'), encoding='utf8', index=False)